// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WeatherService
{

    public class Headline
    {

        [JsonProperty("EffectiveDate")]
        public string EffectiveDate { get; set; }

        [JsonProperty("EffectiveEpochDate")]
        public string EffectiveEpochDate { get; set; }

        [JsonProperty("Severity")]
        public string Severity { get; set; }

        [JsonProperty("Text")]
        public string Text { get; set; }

        [JsonProperty("Category")]
        public string Category { get; set; }

        [JsonProperty("EndDate")]
        public string EndDate { get; set; }

        [JsonProperty("EndEpochDate")]
        public string EndEpochDate { get; set; }

        [JsonProperty("MobileLink")]
        public string MobileLink { get; set; }

        [JsonProperty("Link")]
        public string Link { get; set; }
    }

    public class Minimum
    {

        [JsonProperty("Value")]
        public string Value { get; set; }

        [JsonProperty("Unit")]
        public string Unit { get; set; }

        [JsonProperty("UnitType")]
        public string UnitType { get; set; }
    }

    public class Maximum
    {

        [JsonProperty("Value")]
        public string Value { get; set; }

        [JsonProperty("Unit")]
        public string Unit { get; set; }

        [JsonProperty("UnitType")]
        public string UnitType { get; set; }
    }

    public class Temperature
    {

        [JsonProperty("Minimum")]
        public Minimum Minimum { get; set; }

        [JsonProperty("Maximum")]
        public Maximum Maximum { get; set; }
    }

    public class Day
    {

        [JsonProperty("Icon")]
        public string Icon { get; set; }

        [JsonProperty("IconPhrase")]
        public string IconPhrase { get; set; }
    }

    public class Night
    {

        [JsonProperty("Icon")]
        public string Icon { get; set; }

        [JsonProperty("IconPhrase")]
        public string IconPhrase { get; set; }
    }

    public class DailyForecast
    {

        [JsonProperty("Date")]
        public string Date { get; set; }

        [JsonProperty("EpochDate")]
        public string EpochDate { get; set; }

        [JsonProperty("Temperature")]
        public Temperature Temperature { get; set; }

        [JsonProperty("Day")]
        public Day Day { get; set; }

        [JsonProperty("Night")]
        public Night Night { get; set; }

        [JsonProperty("Sources")]
        public string[] Sources { get; set; }

        [JsonProperty("MobileLink")]
        public string MobileLink { get; set; }

        [JsonProperty("Link")]
        public string Link { get; set; }
    }

    public class Weather
    {

        [JsonProperty("Headline")]
        public Headline Headline { get; set; }

        [JsonProperty("DailyForecasts")]
        public DailyForecast[] DailyForecasts { get; set; }
    }

}
