// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WeatherService
{

    public class Region
    {

        [JsonProperty("ID")]
        public string ID { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }

        [JsonProperty("EnglishName")]
        public string EnglishName { get; set; }
    }

    public class Country
    {

        [JsonProperty("ID")]
        public string ID { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }

        [JsonProperty("EnglishName")]
        public string EnglishName { get; set; }
    }

    public class AdministrativeArea
    {

        [JsonProperty("ID")]
        public string ID { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }

        [JsonProperty("EnglishName")]
        public string EnglishName { get; set; }

        [JsonProperty("Level")]
        public string Level { get; set; }

        [JsonProperty("LocalizedType")]
        public string LocalizedType { get; set; }

        [JsonProperty("EnglishType")]
        public string EnglishType { get; set; }

        [JsonProperty("CountryID")]
        public string CountryID { get; set; }
    }

    public class TimeZone
    {

        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("GmtOffset")]
        public string GmtOffset { get; set; }

        [JsonProperty("IsDaylightSaving")]
        public string IsDaylightSaving { get; set; }

        [JsonProperty("NextOffsetChange")]
        public object NextOffsetChange { get; set; }
    }

    public class Metric
    {

        [JsonProperty("Value")]
        public string Value { get; set; }

        [JsonProperty("Unit")]
        public string Unit { get; set; }

        [JsonProperty("UnitType")]
        public string UnitType { get; set; }
    }

    public class Imperial
    {

        [JsonProperty("Value")]
        public string Value { get; set; }

        [JsonProperty("Unit")]
        public string Unit { get; set; }

        [JsonProperty("UnitType")]
        public string UnitType { get; set; }
    }

    public class Elevation
    {

        [JsonProperty("Metric")]
        public Metric Metric { get; set; }

        [JsonProperty("Imperial")]
        public Imperial Imperial { get; set; }
    }

    public class GeoPosition
    {

        [JsonProperty("Latitude")]
        public string Latitude { get; set; }

        [JsonProperty("Longitude")]
        public string Longitude { get; set; }

        [JsonProperty("Elevation")]
        public Elevation Elevation { get; set; }
    }

    public class SupplementalAdminArea
    {

        [JsonProperty("Level")]
        public string Level { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }

        [JsonProperty("EnglishName")]
        public string EnglishName { get; set; }
    }

    public class Location
    {

        [JsonProperty("Version")]
        public string Version { get; set; }

        [JsonProperty("Key")]
        public string Key { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Rank")]
        public string Rank { get; set; }

        [JsonProperty("LocalizedName")]
        public string LocalizedName { get; set; }

        [JsonProperty("EnglishName")]
        public string EnglishName { get; set; }

        [JsonProperty("PrimaryPostalCode")]
        public string PrimaryPostalCode { get; set; }

        [JsonProperty("Region")]
        public Region Region { get; set; }

        [JsonProperty("Country")]
        public Country Country { get; set; }

        [JsonProperty("AdministrativeArea")]
        public AdministrativeArea AdministrativeArea { get; set; }

        [JsonProperty("TimeZone")]
        public TimeZone TimeZone { get; set; }

        [JsonProperty("GeoPosition")]
        public GeoPosition GeoPosition { get; set; }

        [JsonProperty("IsAlias")]
        public bool IsAlias { get; set; }

        [JsonProperty("SupplementalAdminAreas")]
        public SupplementalAdminArea[] SupplementalAdminAreas { get; set; }
    }

}
