// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace RestaurantService
{

    public class Option
    {

        [JsonProperty("formatted_original_price")]
        public string FormattedOriginalPrice { get; set; }

        [JsonProperty("formatted_price")]
        public string FormattedPrice { get; set; }

        [JsonProperty("is_quantity_limited")]
        public bool IsQuantityLimited { get; set; }

        [JsonProperty("original_price")]
        public int OriginalPrice { get; set; }

        [JsonProperty("price")]
        public int Price { get; set; }

        [JsonProperty("purchase_url")]
        public string PurchaseUrl { get; set; }

        [JsonProperty("remaining_count")]
        public int RemainingCount { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }
    }

    public class Deal
    {

        [JsonProperty("currency_code")]
        public string CurrencyCode { get; set; }

        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }

        [JsonProperty("options")]
        public Option[] Options { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("is_popular")]
        public bool IsPopular { get; set; }

        [JsonProperty("time_start")]
        public int TimeStart { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }
    }

    public class Option2
    {

        [JsonProperty("formatted_price")]
        public string FormattedPrice { get; set; }

        [JsonProperty("price")]
        public int Price { get; set; }
    }

    public class GiftCertificate
    {

        [JsonProperty("currency_code")]
        public string CurrencyCode { get; set; }

        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }

        [JsonProperty("options")]
        public Option2[] Options { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("unused_balances")]
        public string UnusedBalances { get; set; }
    }

    public class YelpBusinessCoordinate
    {

        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }

    public class YelpBusinessLocation
    {

        [JsonProperty("address")]
        public string[] Address { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("coordinate")]
        public Coordinate Coordinate { get; set; }

        [JsonProperty("country_code")]
        public string CountryCode { get; set; }

        [JsonProperty("cross_streets")]
        public string CrossStreets { get; set; }

        [JsonProperty("display_address")]
        public string[] DisplayAddress { get; set; }

        [JsonProperty("geo_accuracy")]
        public double GeoAccuracy { get; set; }

        [JsonProperty("neighborhoods")]
        public string[] Neighborhoods { get; set; }

        [JsonProperty("postal_code")]
        public string PostalCode { get; set; }

        [JsonProperty("state_code")]
        public string StateCode { get; set; }
    }

    public class User
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public class Review
    {

        [JsonProperty("excerpt")]
        public string Excerpt { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("rating")]
        public int Rating { get; set; }

        [JsonProperty("rating_image_large_url")]
        public string RatingImageLargeUrl { get; set; }

        [JsonProperty("rating_image_small_url")]
        public string RatingImageSmallUrl { get; set; }

        [JsonProperty("rating_image_url")]
        public string RatingImageUrl { get; set; }

        [JsonProperty("time_created")]
        public int TimeCreated { get; set; }

        [JsonProperty("user")]
        public User User { get; set; }
    }

    public class YelpBusiness
    {

        [JsonProperty("categories")]
        public string[][] Categories { get; set; }

        [JsonProperty("deals")]
        public Deal[] Deals { get; set; }

        [JsonProperty("display_phone")]
        public string DisplayPhone { get; set; }

        [JsonProperty("eat24_url")]
        public string Eat24Url { get; set; }

        [JsonProperty("gift_certificates")]
        public GiftCertificate[] GiftCertificates { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }

        [JsonProperty("is_claimed")]
        public bool IsClaimed { get; set; }

        [JsonProperty("is_closed")]
        public bool IsClosed { get; set; }

        [JsonProperty("location")]
        public YelpBusinessLocation Location { get; set; }

        [JsonProperty("menu_date_updated")]
        public int MenuDateUpdated { get; set; }

        [JsonProperty("menu_provider")]
        public string MenuProvider { get; set; }

        [JsonProperty("mobile_url")]
        public string MobileUrl { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("rating")]
        public double Rating { get; set; }

        [JsonProperty("rating_img_url")]
        public string RatingImgUrl { get; set; }

        [JsonProperty("rating_img_url_large")]
        public string RatingImgUrlLarge { get; set; }

        [JsonProperty("rating_img_url_small")]
        public string RatingImgUrlSmall { get; set; }

        [JsonProperty("review_count")]
        public int ReviewCount { get; set; }

        [JsonProperty("reviews")]
        public Review[] Reviews { get; set; }

        [JsonProperty("snippet_image_url")]
        public string SnippetImageUrl { get; set; }

        [JsonProperty("snippet_text")]
        public string SnippetText { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

}
