// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace RestaurantService
{

    public class R
    {

        [JsonProperty("res_id")]
        public int ResId { get; set; }
    }

    public class ZomatoLocation
    {

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("locality")]
        public string Locality { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("city_id")]
        public int CityId { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("zipcode")]
        public string Zipcode { get; set; }

        [JsonProperty("country_id")]
        public int CountryId { get; set; }
    }

    public class UserRating
    {

        [JsonProperty("aggregate_rating")]
        public string AggregateRating { get; set; }

        [JsonProperty("rating_text")]
        public string RatingText { get; set; }

        [JsonProperty("rating_color")]
        public string RatingColor { get; set; }

        [JsonProperty("votes")]
        public string Votes { get; set; }
    }

    public class RestaurantInfo
    {

        [JsonProperty("R")]
        public R R { get; set; }

        [JsonProperty("apikey")]
        public string Apikey { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("location")]
        public ZomatoLocation Location { get; set; }

        [JsonProperty("cuisines")]
        public string Cuisines { get; set; }

        [JsonProperty("average_cost_for_two")]
        public int AverageCostForTwo { get; set; }

        [JsonProperty("price_range")]
        public int PriceRange { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("offers")]
        public object[] Offers { get; set; }

        [JsonProperty("thumb")]
        public string Thumb { get; set; }

        [JsonProperty("user_rating")]
        public UserRating UserRating { get; set; }

        [JsonProperty("photos_url")]
        public string PhotosUrl { get; set; }

        [JsonProperty("menu_url")]
        public string MenuUrl { get; set; }

        [JsonProperty("featured_image")]
        public string FeaturedImage { get; set; }

        [JsonProperty("has_online_delivery")]
        public int HasOnlineDelivery { get; set; }

        [JsonProperty("is_delivering_now")]
        public int IsDeliveringNow { get; set; }

        [JsonProperty("deeplink")]
        public string Deeplink { get; set; }

        [JsonProperty("events_url")]
        public string EventsUrl { get; set; }

        [JsonProperty("establishment_types")]
        public object[] EstablishmentTypes { get; set; }
    }

    public class Restaurant
    {

        [JsonProperty("restaurant")]
        public RestaurantInfo RestaurantInfo { get; set; }
    }

    public class ZomatoPlaces
    {

        [JsonProperty("results_found")]
        public int ResultsFound { get; set; }

        [JsonProperty("results_start")]
        public int ResultsStart { get; set; }

        [JsonProperty("results_shown")]
        public int ResultsShown { get; set; }

        [JsonProperty("restaurants")]
        public Restaurant[] Restaurants { get; set; }
    }

}
