// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace NewsService
{

    public class Result
    {

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("sectionId")]
        public string SectionId { get; set; }

        [JsonProperty("webTitle")]
        public string WebTitle { get; set; }

        [JsonProperty("webPublicationDate")]
        public string WebPublicationDate { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("webUrl")]
        public string WebUrl { get; set; }

        [JsonProperty("apiUrl")]
        public string ApiUrl { get; set; }

        [JsonProperty("sectionName")]
        public string SectionName { get; set; }
    }

    public class Response
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("userTier")]
        public string UserTier { get; set; }

        [JsonProperty("total")]
        public int Total { get; set; }

        [JsonProperty("startIndex")]
        public int StartIndex { get; set; }

        [JsonProperty("pageSize")]
        public int PageSize { get; set; }

        [JsonProperty("currentPage")]
        public int CurrentPage { get; set; }

        [JsonProperty("pages")]
        public int Pages { get; set; }

        [JsonProperty("orderBy")]
        public string OrderBy { get; set; }

        [JsonProperty("results")]
        public Result[] Results { get; set; }
    }

    public class NewsItem
    {

        [JsonProperty("response")]
        public Response Response { get; set; }
    }

}
