//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5WebApp.TodoListServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TodoList", Namespace="http://schemas.datacontract.org/2004/07/TodolistService")]
    [System.SerializableAttribute()]
    public partial class TodoList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5WebApp.TodoListServiceReference.TodoItem[] TodoItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XsdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XsiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5WebApp.TodoListServiceReference.TodoItem[] TodoItem {
            get {
                return this.TodoItemField;
            }
            set {
                if ((object.ReferenceEquals(this.TodoItemField, value) != true)) {
                    this.TodoItemField = value;
                    this.RaisePropertyChanged("TodoItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xsd {
            get {
                return this.XsdField;
            }
            set {
                if ((object.ReferenceEquals(this.XsdField, value) != true)) {
                    this.XsdField = value;
                    this.RaisePropertyChanged("Xsd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xsi {
            get {
                return this.XsiField;
            }
            set {
                if ((object.ReferenceEquals(this.XsiField, value) != true)) {
                    this.XsiField = value;
                    this.RaisePropertyChanged("Xsi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TodoItem", Namespace="http://schemas.datacontract.org/2004/07/TodolistService")]
    [System.SerializableAttribute()]
    public partial class TodoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlobalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemLabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListDateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListLabelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GlobalID {
            get {
                return this.GlobalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GlobalIDField, value) != true)) {
                    this.GlobalIDField = value;
                    this.RaisePropertyChanged("GlobalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemComplete {
            get {
                return this.ItemCompleteField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCompleteField, value) != true)) {
                    this.ItemCompleteField = value;
                    this.RaisePropertyChanged("ItemComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDateCreated {
            get {
                return this.ItemDateCreatedField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDateCreatedField, value) != true)) {
                    this.ItemDateCreatedField = value;
                    this.RaisePropertyChanged("ItemDateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDueDate {
            get {
                return this.ItemDueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemDueDateField, value) != true)) {
                    this.ItemDueDateField = value;
                    this.RaisePropertyChanged("ItemDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIDField, value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemLabel {
            get {
                return this.ItemLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemLabelField, value) != true)) {
                    this.ItemLabelField = value;
                    this.RaisePropertyChanged("ItemLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNotes {
            get {
                return this.ItemNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNotesField, value) != true)) {
                    this.ItemNotesField = value;
                    this.RaisePropertyChanged("ItemNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListDateCreated {
            get {
                return this.ListDateCreatedField;
            }
            set {
                if ((object.ReferenceEquals(this.ListDateCreatedField, value) != true)) {
                    this.ListDateCreatedField = value;
                    this.RaisePropertyChanged("ListDateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListID {
            get {
                return this.ListIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ListIDField, value) != true)) {
                    this.ListIDField = value;
                    this.RaisePropertyChanged("ListID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListLabel {
            get {
                return this.ListLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.ListLabelField, value) != true)) {
                    this.ListLabelField = value;
                    this.RaisePropertyChanged("ListLabel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TodoListServiceReference.ITodolistService")]
    public interface ITodolistService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/GetTodoList", ReplyAction="http://tempuri.org/ITodolistService/GetTodoListResponse")]
        Assignment5WebApp.TodoListServiceReference.TodoList GetTodoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/GetTodoList", ReplyAction="http://tempuri.org/ITodolistService/GetTodoListResponse")]
        System.Threading.Tasks.Task<Assignment5WebApp.TodoListServiceReference.TodoList> GetTodoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/GetUsersTodoList", ReplyAction="http://tempuri.org/ITodolistService/GetUsersTodoListResponse")]
        Assignment5WebApp.TodoListServiceReference.TodoList GetUsersTodoList(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/GetUsersTodoList", ReplyAction="http://tempuri.org/ITodolistService/GetUsersTodoListResponse")]
        System.Threading.Tasks.Task<Assignment5WebApp.TodoListServiceReference.TodoList> GetUsersTodoListAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/AddTodoItem", ReplyAction="http://tempuri.org/ITodolistService/AddTodoItemResponse")]
        void AddTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/AddTodoItem", ReplyAction="http://tempuri.org/ITodolistService/AddTodoItemResponse")]
        System.Threading.Tasks.Task AddTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/DeleteTodoItem", ReplyAction="http://tempuri.org/ITodolistService/DeleteTodoItemResponse")]
        void DeleteTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/DeleteTodoItem", ReplyAction="http://tempuri.org/ITodolistService/DeleteTodoItemResponse")]
        System.Threading.Tasks.Task DeleteTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/CompleteTodoItem", ReplyAction="http://tempuri.org/ITodolistService/CompleteTodoItemResponse")]
        void CompleteTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/CompleteTodoItem", ReplyAction="http://tempuri.org/ITodolistService/CompleteTodoItemResponse")]
        System.Threading.Tasks.Task CompleteTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/EditTodoItem", ReplyAction="http://tempuri.org/ITodolistService/EditTodoItemResponse")]
        void EditTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodolistService/EditTodoItem", ReplyAction="http://tempuri.org/ITodolistService/EditTodoItemResponse")]
        System.Threading.Tasks.Task EditTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITodolistServiceChannel : Assignment5WebApp.TodoListServiceReference.ITodolistService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodolistServiceClient : System.ServiceModel.ClientBase<Assignment5WebApp.TodoListServiceReference.ITodolistService>, Assignment5WebApp.TodoListServiceReference.ITodolistService {
        
        public TodolistServiceClient() {
        }
        
        public TodolistServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TodolistServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodolistServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodolistServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Assignment5WebApp.TodoListServiceReference.TodoList GetTodoList() {
            return base.Channel.GetTodoList();
        }
        
        public System.Threading.Tasks.Task<Assignment5WebApp.TodoListServiceReference.TodoList> GetTodoListAsync() {
            return base.Channel.GetTodoListAsync();
        }
        
        public Assignment5WebApp.TodoListServiceReference.TodoList GetUsersTodoList(string userId) {
            return base.Channel.GetUsersTodoList(userId);
        }
        
        public System.Threading.Tasks.Task<Assignment5WebApp.TodoListServiceReference.TodoList> GetUsersTodoListAsync(string userId) {
            return base.Channel.GetUsersTodoListAsync(userId);
        }
        
        public void AddTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            base.Channel.AddTodoItem(item);
        }
        
        public System.Threading.Tasks.Task AddTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            return base.Channel.AddTodoItemAsync(item);
        }
        
        public void DeleteTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            base.Channel.DeleteTodoItem(item);
        }
        
        public System.Threading.Tasks.Task DeleteTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            return base.Channel.DeleteTodoItemAsync(item);
        }
        
        public void CompleteTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            base.Channel.CompleteTodoItem(item);
        }
        
        public System.Threading.Tasks.Task CompleteTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            return base.Channel.CompleteTodoItemAsync(item);
        }
        
        public void EditTodoItem(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            base.Channel.EditTodoItem(item);
        }
        
        public System.Threading.Tasks.Task EditTodoItemAsync(Assignment5WebApp.TodoListServiceReference.TodoItem item) {
            return base.Channel.EditTodoItemAsync(item);
        }
    }
}
